### ISSUE TITLE
Can't knit HTML presentation

### ISSUE THREAD

**Issue by adamhsparks** [AAGI-Org-AU-Public/AAGITemplates#14]
After creating a new RMarkdown file to generate a xaringan presentation from RStudio File -> New -> From Template -> HTML Presentation {AAGITemplates}, I'm unable to knit the presentation.

```r
File assets/mathjax-eq-num.html not found in resource path
Error: pandoc document conversion failed with error 99
Execution halted
```

Am I missing something in the execution?

I note that the "Presentation Ninja" (default template provided by {xaringan} for English knits.

**Comment by RussellAndrewEdson** [comment]
Yep confirmed, I've got the same behaviour on a virtual machine on my end (barebones RHEL9, with only tidyverse + TexLive installed before installing the AAGITemplates package and trying to immediately knit the new xaringan document):
![image](https://github.com/user-attachments/assets/cd332be6-1f88-4f52-8b45-6e5adc1adc13)

I'll investigate.

**Comment by RussellAndrewEdson** [comment]
Fixed, it was a line about ignoring `.html` files in the `.Rbuildignore` that caused the grief. That mathjax file never gets copied over to the package during the install, and thence never ends up in the assets folder for a new presentation.

I've taken the line out and it solves the issue (@rogerssam we should probably check that this fix hasn't resulted in unwanted html files being copied over though. It doesn't _look_ like it has.)
